spring:
  datasource:
    url: jdbc:mysql://localhost/schoolMate?useUnicode=true&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
